/* Resource Datei Indizes fÅr BUBGEM_E */

#define BGMAIN           0   /* Formular/Dialog */
#define BGMFRAME         1   /* BUTTON in Baum BGMAIN */
#define BGMBUBBLES       3   /* BUTTON in Baum BGMAIN */
#define BGMWINSTYLE      4   /* BUTTON in Baum BGMAIN */
#define BGMFONTCHANGED   5   /* BUTTON in Baum BGMAIN */
#define BGMSENDKEY       6   /* BUTTON in Baum BGMAIN */
#define BGMSAVE          7   /* BUTTON in Baum BGMAIN */
#define BGMCANCEL        8   /* BUTTON in Baum BGMAIN */
#define BGMOK            9   /* BUTTON in Baum BGMAIN */
